using System;
using System.Collections.Generic;

namespace CorporateApp.Core.Entities.DiaEntities
{
    public class PersonelResponse
    {
        public class Result
        {
            public string _cdate { get; set; }
            public string _date { get; set; }
            public string _key { get; set; }
            public string _key_bcs_acentebankahesabi { get; set; }
            public string _key_bcs_bankahesabi { get; set; }
            public string _key_bcs_icranafaka_bankahesabi { get; set; }
            public string _key_per_istenayrilmanedenleri { get; set; }
            public string _key_per_istenayrilmanedenleri_iskur { get; set; }
            public string _key_per_izingrubu { get; set; }
            public string _key_per_mesaigunleri { get; set; }
            public string _key_per_personel_devreden { get; set; }
            public string _key_prj_proje { get; set; }
            public string _key_scf_acentecari { get; set; }
            public string _key_scf_carikart { get; set; }
            public string _key_sis_departman { get; set; }
            public string _key_sis_doviz { get; set; }
            public string _key_sis_doviz_acentecari { get; set; }
            public string _key_sis_doviz_banka { get; set; }
            public string _key_sis_doviz_cari { get; set; }
            public string _key_sis_ozelkod1 { get; set; }
            public string _key_sis_ozelkod2 { get; set; }
            public string _key_sis_resim { get; set; }
            public string _key_sis_sehir { get; set; }
            public string _key_sis_seviyekodu { get; set; }
            public string _key_sis_sube { get; set; }
            public string _key_sis_ulkeler { get; set; }
            public string _key_sis_vergidairesi { get; set; }
            public string _level1 { get; set; }
            public string _level2 { get; set; }
            public string _owner { get; set; }
            public string _serial { get; set; }
            public string _user { get; set; }
            public string acentecarikodu { get; set; }
            public string acentecariunvan { get; set; }
            public string acentehavalebankaadi { get; set; }
            public string acentehavalebankahesabi { get; set; }
            public string acentehavalebankahesapkodu { get; set; }
            public string aciklama1 { get; set; }
            public string aciklama2 { get; set; }
            public string aciklama3 { get; set; }
            public string acikrizaformuonayi { get; set; }
            public string adi { get; set; }
            public string adisoyadi { get; set; }
            public string agicckbilgileriniyakindanal { get; set; }
            public string agiuygulansin { get; set; }
            public string ailesirano { get; set; }
            public string aileyardimi { get; set; }
            public string anneadi { get; set; }
            public string anonimlestirilmebilgisi { get; set; }
            public string asgariucretistisnasi { get; set; }
            public string asgariucretli { get; set; }
            public string askerlikdurumu { get; set; }
            public string babaadi { get; set; }
            public string bagkurno { get; set; }
            public string bankaadi { get; set; }
            public string bankahesapno { get; set; }
            public string bankasubesi { get; set; }
            public string barinmaadresi { get; set; }
            public string belgeturu { get; set; }
            public string bes_durumu { get; set; }
            public string bes_kesinti_yuzdesi { get; set; }
            public string bes_police_no { get; set; }
            public string bireyselemeklilik_isveren { get; set; }
            public string bireyselemeklilik_personel { get; set; }
            public string carikodu { get; set; }
            public string cariunvan { get; set; }
            public string ciltno { get; set; }
            public string cinsiyet { get; set; }
            public string cocuksayisi { get; set; }
            public string cocukyardimi { get; set; }
            public string cocukyardimicocuksayisi { get; set; }
            public string csgbiskolu { get; set; }
            public string damgamuafiyetineteekle { get; set; }
            public string damgavergisi_muafiyetorani { get; set; }
            public string damgavergisihesaplanacak { get; set; }
            public string departmanaciklama { get; set; }
            public string digercocuksayisi { get; set; }
            public string dini { get; set; }
            public string dogumtarihi { get; set; }
            public string dogumyeri { get; set; }
            public string dovizkuru { get; set; }
            public string dovizturu { get; set; }
            public string durum { get; set; }
            public string duzenlemesonbordro { get; set; }
            public string egitimtazminati { get; set; }
            public string ehliyet { get; set; }
            public string ekleyenkullaniciadi { get; set; }
            public string emeklisandigino { get; set; }
            public string eposta { get; set; }
            public string esicalisiyormu { get; set; }
            public string esiningelirivarmi { get; set; }
            public string eskihukumlu { get; set; }
            public string fax { get; set; }
            public string fazlamesai1saat { get; set; }
            public string fazlamesai2saat { get; set; }
            public string gecemesaisisaat { get; set; }
            public string gelireiliskinaciklama { get; set; }
            public string gelirvergisihesaplanacak { get; set; }
            public string gorevi { get; set; }
            public string gorevkodu { get; set; }
            public string grupkodaciklama { get; set; }
            public string gssisci_muafiyetorani { get; set; }
            public string gssisveren_muafiyetorani { get; set; }
            public string gvmatrahmuafiyeti { get; set; }
            public string gvmatrahmuafiyetibaslangic { get; set; }
            public string gvmatrahmuafiyetioran { get; set; }
            public string gvmatrahmuafiyetituru { get; set; }
            public string gvmuafiyetineteekle { get; set; }
            public string gvmuafiyetorani { get; set; }
            public string haftasonumesaisigun { get; set; }
            public string havalebankaadi { get; set; }
            public string havalebankahesabi { get; set; }
            public string havalebankahesapkodu { get; set; }
            public string heskodu { get; set; }
            public string ianaciklama { get; set; }
            public string ianaciklama_iskur { get; set; }
            public string iankodu { get; set; }
            public string iankodu_iskur { get; set; }
            public string icranafakabankaadi { get; set; }
            public string icranafakabankabilgi { get; set; }
            public string icranafakabankahesabi { get; set; }
            public string icranafakabankahesapkodu { get; set; }
            public string il { get; set; }
            public string ilce { get; set; }
            public string iletisimadres1 { get; set; }
            public string iletisimadres2 { get; set; }
            public string iletisimbulvar { get; set; }
            public string iletisimcadde { get; set; }
            public string iletisimdiskapi { get; set; }
            public string iletisimickapi { get; set; }
            public string iletisimilce { get; set; }
            public string iletisimkoy { get; set; }
            public string iletisimmahalle { get; set; }
            public string iletisimpostakodu { get; set; }
            public string iletisimsehiradi { get; set; }
            public string iletisimsehirplaka { get; set; }
            public string iletisimsokak { get; set; }
            public string isebaslamatarihi { get; set; }
            public string iskurmeslekkodu { get; set; }
            public string issizlikiscipayi_muafiyetorani { get; set; }
            public string issizlikisverenpayi_muafiyetorani { get; set; }
            public string issizliksigortasinatabi { get; set; }
            public string istenayrilmatarihi { get; set; }
            public string kangrubu { get; set; }
            public string kayitno { get; set; }
            public string kbsbildirimcikis { get; set; }
            public string kbsbildirimgiris { get; set; }
            public string kbspersonelcikisturu { get; set; }
            public string kbspersonelturu { get; set; }
            public string kidemtarihi { get; set; }
            public string kisacalismatesvikbaslangic { get; set; }
            public string kisacalismatesvikbitis { get; set; }
            public string kisacalismatesvikgunsayisi { get; set; }
            public string kisavadeliskisveren_muafiyetorani { get; set; }
            public string kullaniciadi { get; set; }
            public string kumgelirvergisitutari { get; set; }
            public string maas { get; set; }
            public string mahallekoy { get; set; }
            public string manuelcikis { get; set; }
            public string manuelgiris { get; set; }
            public string medenihali { get; set; }
            public string meslegi { get; set; }
            public string mezuniyettarihi { get; set; }
            public string mezuniyetyil { get; set; }
            public string mezunoldugubolum { get; set; }
            public string mezunolduguokul { get; set; }
            public string odemesekli { get; set; }
            public string odemeturu { get; set; }
            public string ogrenimdurumu { get; set; }
            public string oncekicalismasuresiay { get; set; }
            public string oncekiisyeriadi { get; set; }
            public string oncekiisyeriadresi1 { get; set; }
            public string oncekiisyeriadresi2 { get; set; }
            public string oncekisoyadi { get; set; }
            public string otuzgundenaz { get; set; }
            public string ozelhayatsigortasi_isveren { get; set; }
            public string ozelhayatsigortasi_personel { get; set; }
            public string ozelkodaciklama { get; set; }
            public string ozelsagliksigortasi_isveren { get; set; }
            public string ozelsagliksigortasi_personel { get; set; }
            public string ozelsagliksigortasinetbrut_isveren { get; set; }
            public string pasaportno { get; set; }
            public string pers_asgariucretli { get; set; }
            public string personelturu { get; set; }
            public string projekodu { get; set; }
            public string referans { get; set; }
            public string sakatlikderecesi { get; set; }
            public string sakatlikindirimiuygulansin { get; set; }
            public string sandikkodu { get; set; }
            public string sandiksicilno { get; set; }
            public string serino { get; set; }
            public string sicilno { get; set; }
            public string sigortagrubu { get; set; }
            public string sigortahesaplanacak { get; set; }
            public string sigortakolu { get; set; }
            public string sigortano { get; set; }
            public string sirano { get; set; }
            public string sonbordroayyil { get; set; }
            public string sonbordrotarihi { get; set; }
            public string sonbordroyilay { get; set; }
            public string sosyalguvenlikkuruluskodu { get; set; }
            public string soyadi { get; set; }
            public string sozlesmebitistarihi { get; set; }
            public string sozlesmesekli { get; set; }
            public string sube { get; set; }
            public string tabioldugukanun { get; set; }
            public string tckimlikno { get; set; }
            public string telefon1 { get; set; }
            public string telefon2 { get; set; }
            public string terormagduru { get; set; }
            public string ucretturu { get; set; }
            public string uyrugu { get; set; }
            public string uzunvadeliskisci_muafiyetorani { get; set; }
            public string uzunvadeliskisveren_muafiyetorani { get; set; }
            public string vergidairesi { get; set; }
            public string verginumarasi { get; set; }
            public string verildigiyer { get; set; }
            public string verilisnedeni { get; set; }
            public string verilistarihi { get; set; }
            public string yemekyardimi { get; set; }
            public string yemekyardimigun { get; set; }
            public string yemekyardimigunturu { get; set; }
            public string yetkikodu { get; set; }
        }

        public class Root
        {
            public string code { get; set; }
            public string msg { get; set; }
            public List<Result> result { get; set; }
        }
    }
}